version: '3'

services:

  mariadb:
    image: mariadb:10.4.12
    container_name: mariadb_ecomusic
    restart: unless-stopped
    command: --character_set_client=utf8 --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "3310:3306"
    environment:
      - MYSQL_DATABASE=dolibarr
      - MYSQL_USER=dolibarr
      - MYSQL_PASSWORD=dolibarr
      - MYSQL_RANDOM_ROOT_PASSWORD=yes

  dolibarr:
    image: upshift/dolibarr:latest
    container_name: dolibarr_ecomusic
    restart: unless-stopped
    depends_on:
        - mariadb
    ports:
        - "8090:80"
    environment:
      - DOLI_ADMIN_LOGIN=dolibarr
      - DOLI_ADMIN_PASSWORD=dolibarr
      - DOLI_DB_HOST=mariadb
      - DOLI_DB_NAME=dolibarr
      - DOLI_DB_USER=dolibarr
      - DOLI_DB_PASSWORD=dolibarr
      - TZ=Europe/Madrid 
      - LANG=es_ES
    volumes:
      - ./doli_html:/var/www/html
      - ./doli_docs:/var/www/documents